book_index:
    path:     /
    defaults: { _controller: "AppBundle:Book:index" }
    methods:  GET

book_author:
    path:     /author/{id}
    defaults: { _controller: "AppBundle:Book:author" }
    methods:  GET

book_genre:
    path:     /genre/{id}
    defaults: { _controller: "AppBundle:Book:genre" }
    methods:  GET

book_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Book:show" }
    methods:  GET

book_new:
    path:     /new
    defaults: { _controller: "AppBundle:Book:new" }
    methods:  [GET, POST]

book_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Book:edit" }
    methods:  [GET, POST]

book_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Book:delete" }
    methods:  DELETE
