AppBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    manyToMany:
        favouriteBooks:
            targetEntity: AppBundle\Entity\Book
            joinTable:
                name: user_favourite_book
                joinColumns:
                    user_id:
                        regerencedColumnName: id
                inverseJoinColumns:
                    book_id:
                        referencedColumnName: id